# Configuration for markdownlint

# It doesn't seem like we can disable MD033 entirely only allow the HTML we're going to use
MD033:
  allowed_elements:
    - cite

MD013:
  line_length: 180
  heading_line_length: 80
  code_block_line_length: 80
  code_blocks: true
  tables: true
  headings: true
  strict: false
  stern: false